name: Tradein
version: 1.0
author: Nicholai
main: com.nicholai.tradein.Tradein
api-version: 1.16
commands:
  tradexp:
    description: trade xp
    usage: /<command>
  timefly:
    description: fly
    usage: /<command>
  tradein:
    description: command help
    usage: /<command>